plugins {
    id 'org.springframework.boot' version "$springBootVersion"
    id 'io.spring.dependency-management' version "$springDependencyManagerVersion"
    id 'com.google.cloud.tools.jib' version '3.4.3'
}

apply from: "common/gradle/common.gradle"
apply from: "common/gradle/jib.gradle"

group = 'az.att.asan'

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

dependencies {

    /* ================= CORE MODULES ================= */
    implementation project(":common")
    implementation project(":common-security")

    /* ================= SPRING BOOT ================= */
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
   // implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-aop'

    /* ================= LOMBOK ================= */
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    /* ================= MAPSTRUCT ================= */
    implementation "org.mapstruct:mapstruct:$mapstructVersion"
    annotationProcessor "org.mapstruct:mapstruct-processor:$mapstructVersion"

    /* ================= CONFIG PROCESSOR ================= */
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    /* ================= UTILS ================= */
    implementation "org.apache.commons:commons-lang3:$apacheCommonsVersion"
    implementation 'org.apache.commons:commons-text:1.10.0'
    implementation "org.modelmapper:modelmapper:$modelmapperVersion"

    /* ================= JWT ================= */
    implementation "io.jsonwebtoken:jjwt-api:${jjwtVersion}"
    implementation "io.jsonwebtoken:jjwt-impl:${jjwtVersion}"
    implementation "io.jsonwebtoken:jjwt-jackson:${jjwtVersion}"
    implementation 'com.fasterxml.jackson.core:jackson-databind'

    /* ================= OPENAPI ================= */
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'

    /* ================= REDIS ================= */
    implementation "io.lettuce:lettuce-core:$lettuceVersion"

    /* ================= DB ================= */
    runtimeOnly 'org.postgresql:postgresql:42.7.3'
    implementation 'org.flywaydb:flyway-core'

    /* ================= KAFKA ================= */
    implementation 'org.springframework.kafka:spring-kafka'

    /* ================= TEST ================= */
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()
}

// Show unchecked warnings during compilation
tasks.withType(JavaCompile) {
    options.compilerArgs << "-Xlint:unchecked"
}
