apply plugin: 'com.google.cloud.tools.jib'

def platformList = ((findProperty('platforms') ?: 'amd64,arm64') as String)
        .split(',')
        .collect { it.trim() }
        .findAll { it }

//jib {
//    from {
//        image = 'eclipse-temurin:21-jre'
//        platforms {
//            platformList.each { arch ->
//                platform { architecture = arch; os = 'linux' }
//            }
//        }
//    }
//    to {
//        def baseVersion = version.toString()
//        def ciId = System.getenv("CI_PIPELINE_IID") ?: "local"
//        def tagPart = "notag"
//
//        try {
//            def tag = runGit("git describe --tags --abbrev=0")?.trim()
//            if (tag) {
//                tagPart = tag
//            }
//        } catch (e) {
//            println "git describe failed: ${e.message}"
//        }
//
//        def fullVersion = "${baseVersion}.dev.${ciId}"
//
//
//        image = "git.att.az:5050/tedaruk.az/${project.name.toLowerCase()}"
//        tags = [fullVersion] as Set
//
//        println "Docker image: ${image}:${fullVersion}"
//
//        allowInsecureRegistries = true
//
//        auth {
//            username = project.findProperty("dockerUsername")
//            password = project.findProperty("dockerPassword")
//        }
//    }
//}
