ALTER TABLE organizations
    ADD COLUMN name                VARCHAR(255),
    ADD COLUMN address             VARCHAR(255),
    ADD COLUMN phone_number        VARCHAR(255),
    ADD COLUMN email               VARCHAR(255),
    ADD COLUMN region_id           INTEGER,
    ADD COLUMN organization_type   INTEGER DEFAULT 0 NOT NULL,
    ADD COLUMN is_registered       BOOLEAN DEFAULT FALSE NOT NULL,
    ADD COLUMN created_by          VARCHAR(255),
    ADD COLUMN created_on          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN last_modified_by    VARCHAR(255),
    ADD COLUMN last_modified_on    TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN parent_organization_id UUID,
    ADD COLUMN organisation_status INTEGER DEFAULT 0 NOT NULL,
    ADD COLUMN logo_name           VARCHAR(255),
    ADD COLUMN about               TEXT,
    ADD COLUMN ownership_type_id   INTEGER DEFAULT 100 NOT NULL,
    ADD COLUMN visible_on_public   BOOLEAN DEFAULT TRUE NOT NULL,
    ADD COLUMN is_first_entry      BOOLEAN DEFAULT TRUE NOT NULL;
