CREATE TABLE roles
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255)                            NOT NULL,
    created_by       VARCHAR(255),
    created_on       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_on TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by VARCHAR(255),
    is_from_system   BOOLEAN                                 NOT NULL,
    organization_id  UUID,
    is_default       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

ALTER TABLE roles
    ADD CONSTRAINT FK_ROLES_ON_ORGANIZATION
        FOREIGN KEY (organization_id) REFERENCES organizations (id);
