CREATE TABLE languages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    locale      VARCHAR(255),
    message_key VARCHAR(255),
    message     VARCHAR(255),
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

ALTER TABLE languages
    ADD CONSTRAINT uc_7a3b91cd1ccc67f2c969b15e0 UNIQUE (locale, message_key);
