CREATE TABLE languages
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    locale      VARCHAR(255),
    message_key VARCHAR(255),
    message     VARCHAR(255),
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

ALTER TABLE languages
    ADD CONSTRAINT uc_languages_locale_message_key UNIQUE (locale, message_key);
