CREATE TABLE user_role
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id                  BIGINT                                  NOT NULL,
    tin                     VARCHAR(255)                            NOT NULL,
    asan_user_certificate_id UUID                                    NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id)
);

ALTER TABLE user_role
    ADD CONSTRAINT FK_USER_ROLE_ON_ASAN_USER_CERTIFICATE
        FOREIGN KEY (asan_user_certificate_id) REFERENCES asan_user_certificates (id);

ALTER TABLE user_role
    ADD CONSTRAINT FK_USER_ROLE_ON_ROLE
        FOREIGN KEY (role_id) REFERENCES roles (id);
