CREATE TABLE user_role
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_id                  BIGINT                                  NOT NULL,
    tin                      VARCHAR(255)                            NOT NULL,
    asan_user_certificate_id UUID                                    NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id)
);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_asan_user_certificate
        FOREIGN KEY (asan_user_certificate_id) REFERENCES asan_user_certificates (id);

ALTER TABLE user_role
    ADD CONSTRAINT fk_user_role_on_role
        FOREIGN KEY (role_id) REFERENCES roles (id);
